// setores.js

const SETORES_HOSPITAL_CONDE = [
  "Acompanhamento Neonatal",
  "Almoxarifado",
  "Almoxarifado (Container M.Hospitalar)",
  "Arquivo",
  "Assessoria da Direção de Enfermagem",
  "CAF",
  "CAF (Container)",
  "CAF / Material Hospitalar",
  "CAF Corredor Externo",
  "Cartório",
  "CCIH",
  "Centro Cirúrgico",
  "Centro Cirúrgico / Star",
  "Classificação de Risco 1",
  "Classificação de Risco 2",
  "Classificação de Risco Maternidade",
  "Clínica Médica Masculina 1",
  "Clínica Médica Masculina 2",
  "Clínica Médica Masculina 3",
  "Consultório 1 Maternidade",
  "Consultório 2 Maternidade",
  "Consultório Clínico 1",
  "Consultório Clínico 2",
  "Consultório Clínico 3",
  "Consultório Clínico 4",
  "Corredor da Classificação de Risco da Maternidade",
  "Corredor da Entrada da Maternidade",
  "Corredor da Maternidade e Acesso ao Centro Cirúrgico",
  "Corredor da Sala de Medicação da Maternidade",
  "Corredor Medicamento Adulto",
  "Corredor Refeitório",
  "CME",
  "Dala de Equipamentos da Hemodiálise",
  "Direção Administração",
  "Direagem de Enfermagem",
  "Escada do Prédio da Administração",
  "Escritório CAF",
  "Escritório Malta",
  "Estar Ambulância",
  "Estar Enfermagem (Maternidade)",
  "Estar Médico da Maternidade",
  "Estoque Patrimônio",
  "Estoque Nutrição",
  "Farmácia",
  "Farmácia Satélite",
  "Faturamento",
  "Fonoaudiologia / Fisioterapia / Odontologia",
  "Gerência Multidisciplinar",
  "Guarita Rampa",
  "HIV",
  "Humanização",
  "Imobilização / Ortopedia",
  "Imobilização / Ortopedia Consultório 1",
  "Imobilização / Ortopedia Consultório 2",
  "Isolamento",
  "Laboratório",
  "Limpeza/Diluidor",
  "Manutenção (Container)",
  "Maternidade Alojamento Conjunto 1",
  "Maternidade Alojamento Conjunto 2",
  "Maternidade Posto de Enfermagem",
  "Medicação Adulto",
  "NIR",
  "Nutrição",
  "PJ",
  "Portaria Estacionamento",
  "Pós Operatório 1",
  "Pós Operatório 2",
  "Pós Operatório 3",
  "Posto de Enfermagem Clínica Médica Masculina",
  "Posto do Pós Operatório",
  "Pré Parto",
  "Psicologia",
  "Qualidade",
  "Recepção Direção",
  "Recepção Principal",
  "Recepção Star Médico",
  "Refeitório",
  "RH",
  "Rouparia",
  "Rouparia (Container)",
  "Saúde Mental / Corredor",
  "Sala (Round)",
  "Sala Administração Técnica e Assessoria",
  "Sala ao Lado do RH",
  "Sala da Coordenação Empresa de Limpeza",
  "Sala de Coleta",
  "Sala de Entrega de Resultados",
  "Sala de Manutenção Ar Condicionado",
  "Sala de Manutenção Predial",
  "Sala de Medicação Maternidade",
  "Sala de Procedimentos",
  "Sala de Reunião",
  "Sala de Sutura",
  "Sala de Ultrasonografia",
  "Sala Epidemiologia",
  "Sala Leito Adulto Saúde Mental",
  "Sala Leito Infanto Juvenil Saúde Mental",
  "Sala Material Limpeza",
  "Sala Multidisciplinar Saúde Mental",
  "Sala Patrimônio",
  "SAME",
  "Serviço Social",
  "SESMIT",
  "Star Enfermagem 1ºAndar",
  "Star Enfermagem 2ºAndar",
  "Star Médico",
  "Supervisão Adm",
  "TI",
  "Tomografia",
  "Trauma",
  "Unidade Intermediária de Internação Neonatal",
  "UPG"
];

const SETORES_UPA_INOA = [
  "Administração",
  "Almoxarifado",
  "Área Kids Recepção",
  "Banheiro",
  "CAF",
  "Classificação de Risco 1",
  "Classificação de Risco 2",
  "Consultório 1",
  "Consultório 2",
  "Consultório 3",
  "Consultório 4",
  "Consultório 5",
  "Consultório 6",
  "Consultório 7",
  "Corredor",
  "Corredor Observação Adulto",
  "Corredor Raio-X",
  "Direção",
  "DML",
  "Eletrocardiograma",
  "Estar / Sala de Reunião",
  "Estoque Patrimônio",
  "Farmácia",
  "Isolamento 1",
  "Isolamento 2",
  "Laboratório",
  "Medicação e Nebulização",
  "NIR",
  "Odontologia",
  "Ouvidoria",
  "Pediatria",
  "Raio-X",
  "Recepção / Corredores",
  "Refeitório / Copa",
  "Repouso Feminino",
  "Repouso Masculino",
  "Repouso Multiprofissional",
  "Recursos Humanos",
  "Rouparia",
  "Sala de Equipamentos",
  "Sala de Utilidades",
  "Sala Multiuso (Utilizadores)",
  "Sala Observação Adulto",
  "Sala Vermelha",
  "SAME / Arquivo",
  "Serviço Social",
  "Vestiário Feminino"
];

const SETORES_UPA_SANTA_RITA = [
  "Administração",
  "CAF",
  "Classificação de Risco 1",
  "Classificação de Risco 2",
  "Consultório 1",
  "Consultório 2",
  "Consultório 3",
  "Consultório 4",
  "Corredor da Medicação Adulto",
  "Corredor Morgue",
  "Cozinha / Copa",
  "Depósito de Material Hospitalar",
  "DML",
  "Estar de Enfermagem",
  "Estar Médico",
  "Estoque Patrimônio",
  "Farmácia",
  "Laboratório",
  "Medicação Adulto",
  "Medicação Pediátrica",
  "Morgue",
  "Ouvidoria",
  "Recepção",
  "Sala de Manutenção",
  "Sala de Medicação Auxiliar",
  "Sala de Procedimentos",
  "Trauma / Procedimentos"
];

const SETORES_SAMU_BARROCO = [
  "Cozinha / Copa",
  "Recepção",
  "Sala de Descanso 1",
  "Sala de Descanso 2",
  "Sala de Limpeza"
];

const SETORES_SAMU_CENTRO = [
  "Administração",
  "Centro de Instrução",
  "Cozinha / Copa",
  "DML",
  "Dormitório Feminino",
  "Dormitório Masculino",
  "Farmácia",
  "Sala da Coordenação 1"
];

const SETORES_SAMU_PONTA_NEGRA = [
  "Administração",
  "Alojamento 1",
  "Alojamento 2",
  "Ambulância",
  "Área Externa",
  "Centro de Convivência",
  "Depósito de Material Hospitalar",
  "DML"
];

// O SEGREDO ESTÁ AQUI: Um mapa chave-valor vinculando a Unidade aos Setores dela.
// Certifique-se de que as chaves (ex: 'Hospital Conde') sejam exatamente iguais 
// aos valores que você salva/seleciona no campo "Unidade" do seu formulário.
export const MAPA_SETORES_POR_UNIDADE = {
  "Hospital Conde": SETORES_HOSPITAL_CONDE,
  "Upa Inoã": SETORES_UPA_INOA,
  "Upa Santa Rita": SETORES_UPA_SANTA_RITA,
  "Samu Barroco": SETORES_SAMU_BARROCO,
  "Samu Centro": SETORES_SAMU_CENTRO,
  "Samu Ponta Negra": SETORES_SAMU_PONTA_NEGRA
};